### ISSUE TITLE
Error unboxing

### ISSUE THREAD

**Issue by nschwermann** [atkinsonholly/Drizzle-tutorial-with-React-Hooks#15]
Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/admin/Projects/react-hooks-example/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/admin/Projects/react-hooks-example/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-10-23T02_00_34_240Z-debug.log
✔ Cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/admin/Projects/react-hooks-example/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/admin/Projects/react-hooks-example/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-10-23T02_00_34_240Z-debug.log

at checkExecSyncError (node:child_process:826:11)
at Object.execSync (node:child_process:900:15)
at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:139:1)
at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:183:1
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.4.16 (core: 5.4.16)
Node v16.7.0

**Comment by nschwermann** [comment]
Issue is the truffle installation says to use -g now so there was no package.json fixed by removing -g when installing truffle
